patch('include/mikmod.h.in')
patch('include/mikmod_internals.h')
patch('drivers/drv_pipe.c')
patch('playercode/mdreg.c')
patch('Makefile.in')
patch('libmikmod/Makefile.in', patch_file='libmikmod_Makefile.in.patch')
build(static_lib=True)
collect_licenses('AUTHORS COPYING.LESSER')
